### ISSUE TITLE
Home Page Responsive ness

### ISSUE THREAD

**Issue by tconn89** [jakekausler/Hackathon#23]
We need a max height and hide overflow on guy with backpack image.

The 6 core concepts should be stackable on mobile.

**Comment by tconn89** [comment]
The colors look great so far!  We need to look at reducing text in all text areas and adding more padding around buttons.  Great job so far team

**Comment by jakekausler** [comment]
Fixed with 82dd4aab74be2f9b3e820d9f63374d9002359728
